namespace Pharmacy_api.Models
{
    /// <summary>
    /// Represents a medicine in the pharmacy inventory system.
    /// This is a domain entity that holds all medicine-related information.
    /// </summary>
    public class Medicine
    {
        /// <summary>
        /// Unique identifier for the medicine.
        /// Auto-generated by the repository (1, 2, 3, ...).
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Full name of the medicine.
        /// Example: "Amoxicillin 500mg", "Paracetamol Tablet"
        /// </summary>
        public string FullName { get; set; } = string.Empty;

        /// <summary>
        /// Additional notes or description about the medicine.
        /// Example: "Take with food", "Not for children under 5"
        /// </summary>
        public string Notes { get; set; } = string.Empty;

        /// <summary>
        /// Expiry date of the medicine.
        /// Used to determine if medicine is still usable.
        /// </summary>
        public DateTime ExpiryDate { get; set; }

        /// <summary>
        /// Current quantity of this medicine in stock.
        /// Decremented when a sale is recorded.
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// Price per unit of the medicine.
        /// Used to calculate the total amount in a sale.
        /// Stored with up to 2 decimal places.
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Brand/manufacturer of the medicine.
        /// Example: "GlaxoSmithKline", "Cipla"
        /// </summary>
        public string Brand { get; set; } = string.Empty;
    }
}
