namespace Pharmacy_api.Models
{
    /// <summary>
    /// Represents a sale transaction in the pharmacy system.
    /// This is a domain entity that records every medicine sale for audit and analytics.
    /// </summary>
    public class SaleRecord
    {
        /// <summary>
        /// Unique identifier for the sale transaction.
        /// Auto-generated by the repository (1, 2, 3, ...).
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Foreign key referencing the medicine that was sold.
        /// Used to link the sale to a specific medicine in inventory.
        /// </summary>
        public int MedicineId { get; set; }

        /// <summary>
        /// The quantity of the medicine sold in this transaction.
        /// This amount is deducted from the medicine's inventory.
        /// </summary>
        public int QuantitySold { get; set; }

        /// <summary>
        /// Date and time when the sale was recorded.
        /// Automatically set to the current date/time at the moment of sale.
        /// </summary>
        public DateTime SoldAt { get; set; }

        /// <summary>
        /// The total amount for this sale.
        /// Calculated as: Medicine.Price × QuantitySold
        /// Example: If medicine costs 100 and 5 units sold, TotalAmount = 500
        /// </summary>
        public decimal TotalAmount { get; set; }
    }
}
