using Microsoft.AspNetCore.Mvc;
using Pharmacy_api.Models;
using Pharmacy_api.Services.Interfaces;

namespace Pharmacy_api.Controllers
{
    /// <summary>
    /// Controller for all medicine-related API endpoints.
    /// This controller handles HTTP requests and delegates business logic to the MedicineService.
    /// Applies Single Responsibility Principle (SRP) - only responsible for HTTP communication.
    /// All business logic is delegated to the service layer.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public class MedicinesController : ControllerBase
    {
        // Service dependency injected via constructor (Dependency Injection)
        private readonly IMedicineService _medicineService;

        public MedicinesController(IMedicineService medicineService)
        {
            _medicineService = medicineService;
        }

        /// <summary>
        /// GET: api/medicines
        /// Retrieves all medicines from the system.
        /// </summary>
        /// <returns>
        /// 200 OK: List of all medicines
        /// 500 Internal Server Error: If an unexpected error occurs
        /// </returns>
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<IEnumerable<Medicine>>> GetAllMedicines()
        {
            try
            {
                // Call service to retrieve all medicines
                var medicines = await _medicineService.GetAllMedicinesAsync();
                return Ok(medicines);
            }
            catch (Exception ex)
            {
                // Log error and return 500 Internal Server Error
                return StatusCode(StatusCodes.Status500InternalServerError,
                    new { message = "An error occurred while retrieving medicines.", error = ex.Message });
            }
        }

        /// <summary>
        /// GET: api/medicines/{id}
        /// Retrieves a specific medicine by its unique identifier.
        /// </summary>
        /// <param name="id">The unique identifier of the medicine</param>
        /// <returns>
        /// 200 OK: The medicine with the specified ID
        /// 404 Not Found: If medicine with the given ID does not exist
        /// 500 Internal Server Error: If an unexpected error occurs
        /// </returns>
        [HttpGet("{id}")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<Medicine>> GetMedicineById(int id)
        {
            try
            {
                // Call service to retrieve medicine by ID
                var medicine = await _medicineService.GetMedicineByIdAsync(id);

                // Return 404 Not Found if medicine doesn't exist
                if (medicine == null)
                {
                    return NotFound(new { message = $"Medicine with ID {id} not found." });
                }

                return Ok(medicine);
            }
            catch (Exception ex)
            {
                // Log error and return 500 Internal Server Error
                return StatusCode(StatusCodes.Status500InternalServerError,
                    new { message = "An error occurred while retrieving the medicine.", error = ex.Message });
            }
        }

        /// <summary>
        /// POST: api/medicines
        /// Adds a new medicine to the system.
        /// The ID is auto-generated by the repository.
        /// </summary>
        /// <param name="medicine">The medicine object to add</param>
        /// <returns>
        /// 201 Created: The newly created medicine with auto-generated ID
        /// 400 Bad Request: If validation fails (invalid data)
        /// 500 Internal Server Error: If an unexpected error occurs
        /// </returns>
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<Medicine>> AddMedicine([FromBody] Medicine medicine)
        {
            // Validate model state (checks for required fields and type validation)
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                // Call service to add medicine with business logic validation
                var addedMedicine = await _medicineService.AddMedicineAsync(medicine);

                // Return 201 Created with the newly created medicine and its location
                return CreatedAtAction(nameof(GetMedicineById), new { id = addedMedicine.Id }, addedMedicine);
            }
            catch (ArgumentException ex)
            {
                // Return 400 Bad Request for validation errors
                return BadRequest(new { message = ex.Message });
            }
            catch (Exception ex)
            {
                // Log error and return 500 Internal Server Error
                return StatusCode(StatusCodes.Status500InternalServerError,
                    new { message = "An error occurred while adding the medicine.", error = ex.Message });
            }
        }

        /// <summary>
        /// POST: api/medicines/record-sale
        /// Records a sale of medicine with the following business logic:
        /// 1. Verifies the medicine exists
        /// 2. Checks sufficient stock is available
        /// 3. Reduces the medicine quantity
        /// 4. Creates a sale record with calculated total amount
        /// 5. Persists both changes
        /// </summary>
        /// <param name="request">The sale request containing medicine ID and quantity sold</param>
        /// <returns>
        /// 200 OK: The recorded sale with calculated total amount
        /// 400 Bad Request: If validation fails or insufficient stock
        /// 404 Not Found: If the medicine does not exist
        /// 500 Internal Server Error: If an unexpected error occurs
        /// </returns>
        [HttpPost("record-sale")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<SaleRecord>> RecordSale([FromBody] RecordSaleRequest request)
        {
            // Validate model state
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                // Call service to record the sale with all business logic validation
                var saleRecord = await _medicineService.RecordSaleAsync(request.MedicineId, request.QuantitySold);

                // Return 200 OK with the created sale record
                return Ok(saleRecord);
            }
            catch (InvalidOperationException ex)
            {
                // Return 404 Not Found if medicine doesn't exist
                // Return 400 Bad Request if insufficient stock
                if (ex.Message.Contains("not found"))
                {
                    return NotFound(new { message = ex.Message });
                }

                return BadRequest(new { message = ex.Message });
            }
            catch (ArgumentException ex)
            {
                // Return 400 Bad Request for validation errors
                return BadRequest(new { message = ex.Message });
            }
            catch (Exception ex)
            {
                // Log error and return 500 Internal Server Error
                return StatusCode(StatusCodes.Status500InternalServerError,
                    new { message = "An error occurred while recording the sale.", error = ex.Message });
            }
        }
    }
}
